spring:
  profiles:
    active: dev
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3316/auth?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: _123456_
      schema[0]: classpath:/auth.sql
      initialize: true
  application:
      name: auth-service
  cloud:
    consul:
      host: localhost
#      host: ${CONSUL_ADDRESS:192.168.1.204}
      port: 8500
      discovery:
        ip-address: ${HOST_ADDRESS:localhost}
        port: ${SERVER_PORT:${server.port}}
#        healthCheckPath: /health
        healthCheckInterval: 15s
        instance-id: ${spring.cloud.consul.discovery.service-name}-${spring.profiles.active}-${spring.cloud.consul.discovery.ip-address}-${random.value}
        service-name: auth-service

server:
  port: 8007

management:
  health:
    defaults:
      enabled: false
  endpoint:
    shutdown:
      enabled: false
  security:
    enabled: false

logging:
  level:
    root: info
    com.blueskykong.lottor.core: debug
  path: "./logs"

---
spring:
  cloud:
    stream:
      bindings:
        test-input:
          group: testGroup
          content-type: application/x-java-object;type=com.blueskykong.lottor.common.entity.TransactionMsgAdapter
          destination: tx-auth
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /

---
lottor:
  enabled: true
  core:
    cache-type: redis
    tx-redis-config:
      host-name: localhost
      port: 6379
#      password: _123456_
    serializer: kryo
    netty-serializer: kryo
    blocking-queue-type: Linked
    cache: true
    tx-manager-id: lottor